version: '3.8'
services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    container_name: treningsapp_db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: treningsplanlegger
    volumes:
      - ./postgres_container_data:/var/lib/postgresql/data


    restart: always

  backend:
    build: ./treningsplanlegging
    ports:
      - "8080:8080"
    depends_on:
      - db


  frontend:
    build: ./trenings-app-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"


volumes:
  postgres-data:
