services:
  db:
    ports:
      - 5432:5432
    container_name: treningsapp_db
    image: postgres
    environment:
      - POSTGRES_DB=treningsplanleggingdb
      - POSTGRES_USER=admin2
      - POSTGRES_PASSWORD=admin2
    volumes:
      - C:\postgres_container_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the init.sql file

    restart: always

  backend:
    build: ./treningsplanlegging
    container_name: treningsapp_back
    ports:
      - 8080:8080
    environment:
      db-url: jdbc:postgresql://db:5432/treningsplanleggingdb
      db-user: admin2
      db-password: admin2
    depends_on:
      - db
    restart: always
  frontend:
    build: ./trenings-app-frontend
    container_name: treningsapp_front
    ports:
      - 3000:3000
    depends_on:
      - backend
    restart: always
